apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wisphill/ops-infrastructure
    targetRevision: main
    path: gitops/clusters/apse2/local/http-test
  destination:
    server: https://kubernetes.default.svc
    namespace: mesh-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: networking.istio.io
      kind: VirtualService
      name: http-test
      namespace: mesh-test
      managedFieldsManagers:
        - rollouts-controller
