apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: http-test
  namespace: mesh-test
spec:
  hosts:
    - http-test

  http:
    - name: primaryRoute
      route:
        - destination:
            host: http-test-stable
            subset: stable
          weight: 100

        - destination:
            host: http-test-canary
            subset: canary
          weight: 0
