apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: http-test
  namespace: mesh-test

spec:
  host: http-test

  subsets:
    - name: stable
      labels:
        version: stable

    - name: canary
      labels:
        version: canary
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: http-test
  namespace: mesh-test
spec:
  hosts:
    - http-test

  http:
    - name: primaryRoute
      route:
        - destination:
            host: http-test
            subset: stable
          weight: 100

        - destination:
            host: http-test
            subset: canary
          weight: 0
