apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    server:
      assets-path: /app/assets
    branding:
      custom-footer: |
        <p>Powered by <a href="https://github.com/wisphill">Wisphill</a></p>
      app-name: "My Porfolio - Kubernetes - Gitops"
      app-icon-url: "/assets/app-icon.png"
      app-background-color: "#151519"
    theme:
      custom-css-file: /assets/custom.css
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: clock
                hour-format: 24h
              - type: custom-api
                title: GitHub Repositories
                url: https://api.github.com/user/repos
                cache: 30m
                parameters:
                  affiliation: owner
                  sort: updated
                  visibility: all
                headers:
                  Authorization: Bearer ${GITHUB_TOKEN}
                  Accept: application/vnd.github.v3+json
                  User-Agent: Glance-Dashboard
                template: |
                  <div class="github-repos">
                    <ul class="list list-gap-14 collapsible-container" data-collapse-after="3">
                      {{ range .JSON.Array "" }}
                        <li>
                          <a class="size-h3 color-primary" href="{{ .String "html_url" }}">{{ .String "full_name" }}</a>
                          <h3><a href="" target="_blank"></a></h3>
                          <p>{{ .String "description" }}</p>
                          <ul class="list-horizontal-text device-info">
                            <li data-popover-type="html"><div data-popover-html="">Last Update</div>{{ formatTime "DateOnly" ( parseTime "RFC3339" (.String "updated_at") ) }}</li>
                            <li data-popover-type="html"><div data-popover-html="">Visibility</div>{{ .String "visibility" }}</li>
                            <li data-popover-type="html"><div data-popover-html="">Stars</div>{{ .Int "stargazers_count" }}✩</li>
                            {{ if .String "language" }}
                            <li data-popover-type="html"><div data-popover-html="">Language</div>{{ .String "language" }}</li>
                            {{ end }}
                          </ul>
                        </li>
                      {{ end }}
                    </ul>
                  </div>

          - size: full
            widgets:
              - type: monitor
                title: Services
                cache: 1m
                sites:
                  - title: Portfolio
                    url: https://phil.opswork.io.vn
                    icon: mdi:home
                  - title: My blog
                    url: https://wisphill.github.io
                    icon: mdi:post
                  - title: Authentik
                    url: https://authentik.opswork.io.vn
                    icon: sh:authentik
                  - title: Agro Workflows
                    url: https://argo-workflows.opswork.io.vn
                    icon: sh:argo-cd
                  - title: Agro CD & Kubernetes
                    url: https://argo-cd.opswork.io.vn
                    icon: sh:kubernetes
                  - title: Grafana
                    url: https://grafana.opswork.io.vn
                    icon: sh:grafana
                  - title: Prometheus
                    url: https://prometheus.opswork.io.vn
                    icon: sh:prometheus

          - size: small
            widgets:
              - type: rss
                title: DevOps News
                limit: 10
                collapse-after: 3
                cache: 30m
                feeds:
                  - url: https://devops.com/feed/
                    title: DevOps.com
                  - url: https://kubernetes.io/feed.xml
                    title: Kubernetes Blog
                  - url: https://aws.amazon.com/blogs/devops/feed/
                    title: AWS DevOps Blog

  custom.css: |
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500;600&display=swap');

    body {
      font-family: 'IBM Plex Mono', monospace !important;
    }
