apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    theme:
      custom-css: /app/config/custom.css
    pages:
      - name: Home
        columns:

          - size: small
            widgets:
              - type: search
                search-engine: duckduckgo
              - type: clock
                hour-format: 24h

          - size: full
            widgets:
              - type: monitor
                title: Services
                cache: 1m
                sites:
                  - title: Portfolio
                    url: https://phil.opswork.io.vn
                    icon: mdi:home
                    icon-color: "#E04E39"
                  - title: Authentik
                    url: https://authentik.opswork.io.vn
                    icon: si:authentik
                    icon-color: "#FD4B2D"
                  - title: Agro Workflows
                    url: https://argo-workflows.opswork.io.vn
                    icon: sh:argo-cd
                  - title: Agro CD & Kubernetes
                    url: https://argo-cd.opswork.io.vn
                    icon: sh:kubernetes
                  - title: Grafana
                    url: https://grafana.opswork.io.vn
                    icon: sh:grafana
                  - title: Prometheus
                    url: https://prometheus.opswork.io.vn
                    icon: sh:prometheus
                  - title: Portainer
                    url: https://portainer.example.com
                    icon: si:portainer
                  - title: InfluxDB
                    url: https://influx.example.com
                    icon: si:influxdb
                  - title: What's Up Docker
                    url: https://wud.example.com
                    icon: si:docker

          - size: small
            widgets:
              - type: bookmarks
                groups:
                  - title: Infrastructure
                    links:
                      - title: ArgoCD
                        url: https://argocd.example.com
                      - title: Grafana
                        url: https://grafana.example.com
                      - title: Prometheus
                        url: https://prometheus.example.com
  custom.css: |
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500;600&display=swap');

    body {
      font-family: 'IBM Plex Mono', monospace !important;
    }
