apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/wisphill/ops-infrastructure.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/wisphill/ops-infrastructure
      targetRevision: main
      path: gitops/clusters/apse2/local/seaweedfs
      plugin:
        name: ksops
    - repoURL: https://seaweedfs.github.io/seaweedfs/helm
      chart: seaweedfs
      targetRevision: 4.40.0
      helm:
        valueFiles:
          - $values/gitops/clusters/apse2/local/seaweedfs/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
