master:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    className: nginx
    host: seaweedfs.opswork.io.vn
    path: /

volume:
  enabled: true
  replicas: 1
  dataDirs:
    - name: data
      type: "persistentVolumeClaim"
      storageClass: "local-path-provisioner"
      size: "5Gi"
      maxVolumes: 0

filer:
  enabled: true
  replicas: 1
  ingresses:
    http:
      enabled: true
      className: nginx
      host: seaweedfs.opswork.io.vn
      path: "/sw-filer/?(.*)"

s3:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    className: nginx
    host: seaweedfs-s3.opswork.io.vn
    path: /
