master:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    className: nginx
    host: seaweedfs.opswork.io.vn
    path: /

volume:
  enabled: true
  replicas: 1
  dataDirs:
    - name: data
      type: "local-path-provisioner"
      dir: /data
      maxVolumes: 0
  persistence:
    enabled: true
    size: 5Gi

filer:
  enabled: true
  replicas: 1

s3:
  enabled: true
  replicas: 1
