master:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: seaweedfs.opswork.io.vn
        paths:
          - /

volume:
  enabled: true
  replicas: 1
  dataDirs:
    - name: data
      type: ""
      dir: /data
      maxVolumes: 0
  persistence:
    enabled: true
    size: 5Gi

filer:
  enabled: true
  replicas: 1

s3:
  enabled: true
  replicas: 1
