apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2026.2.1
    helm:
      values: |
        authentik:
          existingSecret:
            secretName: authentik-secret-key
        postgresql:
          image:
            registry: docker.io
            repository: bitnamilegacy/postgresql
            tag: 15.8.0-debian-12-r18
          enabled: true

        redis:
          image:
            registry: docker.io
            repository: bitnamilegacy/redis
            tag: 7.4.1-debian-12-r0
          enabled: true

        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - authentik.opswork.io.vn

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
