apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2026.2.1
    helm:
      values: |
        authentik:
          existingSecret:
            secretName: authentik-secret-keys
          config:
            AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS: "0.0.0.0/0"
            AUTHENTIK_FORCE_HTTPS: "true"
        postgresql:
          image:
            registry: docker.io
            repository: library/postgres
            tag: "17.9-bookworm"
          auth:
            username: authentik
            database: authentik
            existingSecret: postgresql-secret-keys
          primary:
            podSecurityContext:
              fsGroup: 1001
            persistence:
              enabled: true
              size: 4Gi
          enabled: true

        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            # required for the backend protocol
            annotations:
              # 1. Ép HTTPS và truyền X-Forwarded-Proto
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
              nginx.ingress.kubernetes.io/upstream-vhost: "authentik.opswork.io.vn"
            hosts:
              - authentik.opswork.io.vn

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
