apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2026.2.1
    helm:
      values: |
        authentik:
          existingSecret:
            secretName: authentik-secret-keys
        postgresql:
          image:
            registry: docker.io
            repository: library/postgres
            tag: "17.9-bookworm"
          auth:
            username: authentik
            database: authentik
            existingSecret: postgresql-secret-keys
          primary:
            podSecurityContext:
              fsGroup: 1001
            persistence:
              enabled: true
              size: 4Gi
          enabled: true

        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            # required for the backend protocol
            annotations:
              nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
            hosts:
              - authentik.opswork.io.vn

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
