apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret-keys
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:DcuHhSxu6rjJWoFYoq7vke6xzHY=,iv:0uMIxVLXYXJosB71LiyaXFTkM1I76P8o4V+qdi9LRW8=,tag:grsWXyVipmVpElb8DZ/ECw==,type:str]
    postgres-password: ENC[AES256_GCM,data:fNdgv60n4jVgPXcMxidZZPRhnIaP,iv:5mIJddxkd/BzJy9gvZjYm7zRqeieMQu2d1aDLx11aVo=,tag:8P69/ZfSfNQdtSfq1Ukp9w==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:52:21Z"
    mac: ENC[AES256_GCM,data:gPRObd4WIv/iQxR8VoZlR2ISgfcIlBqd6E9YA7GFsSg6ZejXbJjVY1Jt2gFHf+n/gcQw6v0S/5qQFyseB4CmuwmQYlCdWk7Un+AMtlXTbxMkjhTsOhYjFyrRGVDTfCoKFCIjSGB0kJ5XYPDDjMUWUEyDJUAoyw7fzUb22hwyOmY=,iv:guPAQ8aqRC9aLKLXVMqCd4xi9gE0qi/9A75O8pc8j8U=,tag:9aNvuVxCt6leVi7wfi7MCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
