apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-keys
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:HjoULinCYcc3U8NIf7dWh0D9XMw=,iv:2hvxAnNhJYz3qt1V+AZOmPMAfAW/gJx52lyThCTG7dk=,tag:cIPBsgTidZrhk5gyNt7iMw==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:m5Tkxg==,iv:ZnIC7f3imaQplo3Bz0d80xopq18tr0HJ/ePUJcVXLbY=,tag:vxhCFC69i80Gcs5ALh8vuA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:3X/uaxW3ZUBU,iv:Bnioax/MGueTr8mlOwBd4SObCJvNz1UfjLvy/lWvEXk=,tag:JIUvjc49KTD+CNo/meNuqg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:e2e4hS6LOQsK,iv:J0PbrGaM9ybIyLveknnJAJUKuAe+0YeAqGmIY24WAAE=,tag:K5wdfK2En+UU1qUkiLsZMg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:JJxkBpbVdtCPGjGUthqsZg94R78=,iv:F8kY/XXOfIaO7kfqsul1/uif5+dV2/mvaowa82yUgJk=,tag:VB6+jCVXOHCwhvGvtFUF7A==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:TxV46l12H6zexSViYsYe7CZQeXzLD1AY6Dnj0XUk2dU=,iv:LCrk5Sqseq6cjFuKchQjLSaGRora6m2wvtl4PIEN96A=,tag:9/6VWd45pnps62v5gLYinQ==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:52:11Z"
    mac: ENC[AES256_GCM,data:WuaNn6kPhIwF+9OOyBCOgCvUFBUkfHgP9ZmJSNyLIluUZxj6COxTt3o455hTIOYRlPJpCcB07c1eyj5hMSRDe1S7pIypvfjpfL7444icBKlysDmt6X2GnNE6/q5DC2m1LydMiqfrNpQz7WUquizhRrQ4EorpI2AzeBsJXj8/NtY=,iv:tGo+ZYlWiYMkl1yKpSWUuYa5AfkY/lV3BBFvDhv0Jws=,tag:hEgLD74znBAjN5yjbZSITQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
