apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:HjoULinCYcc3U8NIf7dWh0D9XMw=,iv:2hvxAnNhJYz3qt1V+AZOmPMAfAW/gJx52lyThCTG7dk=,tag:cIPBsgTidZrhk5gyNt7iMw==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:7fgJUg==,iv:ndUEE6/6wzoVNZwfVkCFC52SSeXoRq834GnzmXikuiw=,tag:XRrkFl9x8vQwUYc4XrRrng==,type:int]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:3X/uaxW3ZUBU,iv:Bnioax/MGueTr8mlOwBd4SObCJvNz1UfjLvy/lWvEXk=,tag:JIUvjc49KTD+CNo/meNuqg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:e2e4hS6LOQsK,iv:J0PbrGaM9ybIyLveknnJAJUKuAe+0YeAqGmIY24WAAE=,tag:K5wdfK2En+UU1qUkiLsZMg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:eZay32GcvKAS,iv:3LeIRNHHdzO1gXr4f/seVERy5tpzW+2SBe5ureTaYgE=,tag:+3ASyIRlY8WRTaRB07inPg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:TxV46l12H6zexSViYsYe7CZQeXzLD1AY6Dnj0XUk2dU=,iv:LCrk5Sqseq6cjFuKchQjLSaGRora6m2wvtl4PIEN96A=,tag:9/6VWd45pnps62v5gLYinQ==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T11:48:30Z"
    mac: ENC[AES256_GCM,data:+UcWPGYS6JKZzWoD+Bc2FjZb65DTaCVSSdTM87xolR0qdpeHG7b48Umdjtb9q+4V9ICeZMXGQH+QtKOH6ZASDFGyNKVLx8SEjgcV9iOnZ4ef2u4xmyNf+TV3jRhajbWh/irk4f1teQg6Z3wStbPUtssNhyPy/CFr0RWwgShdaq8=,iv:OaiYXURApyWAfnS4MPQsCJb/yDBPD/6PaGQEOmferxE=,tag:m3GvclvYbf7nrTn6rhB/hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
