apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:TxV46l12H6zexSViYsYe7CZQeXzLD1AY6Dnj0XUk2dU=,iv:LCrk5Sqseq6cjFuKchQjLSaGRora6m2wvtl4PIEN96A=,tag:9/6VWd45pnps62v5gLYinQ==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:00:45Z"
    mac: ENC[AES256_GCM,data:OvHOqFkNCrLZaVPf4pF73822yC6zvjigmhw2VsSNX7aofwN98Yx5Yub+HSiC4TFdOuvdata6EO0XWy2DRu0XRxZUULnBjDU7nZE8pkTz6JJMI4PNQjzeO1kXFWqhAa7F0hAsv/zqCQJJFhhWZQJ0SLmemdCXobxX9PgTigEM0pg=,iv:tv596s/5bAjQ4ZH1SLfGVtccvKDWlM4zTx5KHllV6Iw=,tag:We6KpHohlgV0H9e0IDJZHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
