apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-workflows/argo-workflows.yaml
  - authentik/authentik.yaml
  - cluster-resources/cluster-resources.yaml
  - grafana-resources.yaml
  - mcp-playwright.yaml
  - metal-lb-manager.yaml
  - nginx-helm.yaml
  - oauth2-proxy-resources.yaml
  - prometheus/prometheus-resources.yaml
  - glance/glance.yaml
