apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: platform
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:jzmvJ0g=,iv:pHU1Mvo11IWQJHqdQGlIhMRAvuhcIFPU0dt2FSxyadw=,tag:w+AzUqCEKYHNzLbriv236w==,type:str]
    admin-password: ENC[AES256_GCM,data:6y6EmbUikC9SNQ==,iv:D530mBGBT9AjQWzi+9bgVnif/guXfGWgxEHCWjPlmug=,tag:RP5ZwQxKZ6JDiZkMa+QjyA==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T14:42:04Z"
    mac: ENC[AES256_GCM,data:b9OSYv50iSwEwVCpvcTB+34b3hw2vtgWJR//oblWQMZRmizO5xGAWxvi5WMsnXlciuJ4G1mUsKOSmfN3gwM1aRzPA2sD5eZh3rsjcACk/81zliwyZbHEfD13sjrBsOKcEaPmgUeOHDnDq8rWUIFlPjLCuRYxqRJwypi9eltzi8Q=,iv:Qoe+VkHp1LVAREJ4aKFjo4tIccmTAjzaHqB8Hp1xZaQ=,tag:us9I2CRixNGTuSUVooJZGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
