apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: app-a-build-
  namespace: argocd

spec:
  workflowTemplateRef:
    name: buildkit-git-image

  arguments:
    parameters:
      - name: repo
        value: https://github.com/wisphill/apps.gin
