apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 0.47.4
      helm:
        valueFiles:
          - $values/gitops/argo-workflows/values.yaml

    - repoURL: https://github.com/wisphill/ops-infrastructure.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/wisphill/ops-infrastructure
      targetRevision: main
      path: gitops/argo-workflows
      plugin:
        name: ksops

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
