apiVersion: v1
kind: Secret
metadata:
    name: argo-workflows-secret-keys
    namespace: argo-workflows
type: Opaque
stringData:
    OKTA_AGROWORKFLOWS_CLIENT_ID: ENC[AES256_GCM,data:h8IEuVwYV2Xcf6GVaVhfIZuJbmI=,iv:PuDK+aR8PSLqhDXJH59Q/DuUa0Alu4xj8ZIZ8w07vds=,tag:8zCN5FdvD6TsNPOYw706XQ==,type:str]
    OKTA_AGROWORKFLOWS_CLIENT_SECRET: ENC[AES256_GCM,data:hsz248Hn9LeLJOX6rOrv/tEtNe+a9q7nGkdpcrqdIpX+wyV5k62LnJU3WFl1NJ1G4rTjpbZVemAWOai8SX79Gg==,iv:T08Ai6qlzsHAipuiMewmrjcOXSqq2S1Qao8fc4REsME=,tag:ITpKP9PBoEvNq6vbMA8++g==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:bQWHXaiDsdme5idMS8qncMHDAwmSw+J+KUCJ6mxgSoN89g9QSQ3LHg==,iv:KIq7KbL9UKx9D4p1egeW285JVqcc4qIFinU9b4rs+IE=,tag:uHW+Oi0CtLa4p/OkYNzWqg==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:8Q5brzmd0MP9fKADbu09k9cknkMAa79R3h5LjycJFoBOwBlP39/J1SnLgsJWuUkLbagN6Gj9mFuag6ltsEV2TEC+zOqpGxYjKid4BMbtvITHUb/QdtIngR4va4vv9GjDehP4V+RuVckwOwY1RbI/4mqN/ifmg9uFdxEfanRVKUk=,iv:kyrKrmRVME+UijDwBZecq/liP6pOy1mi7Cp3RkWThnc=,tag:igBQnO07sDkvjd/ScDo2HQ==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T06:52:42Z"
    mac: ENC[AES256_GCM,data:uvcHhmCknjtyUN9hwNtDZkRfCvMfbmiI8J92nCDMgxvCnZyjaE2Sv36WIQ8AGvTDg8Mcy+JSs/adIs2UQza2jtLUlqNGGNWBY8l/ZyW4E6vA7F/l+tVoP3elXVqwH4v+BW8FvHbZhVn2QJTZVmBt0fQFLl57XOG0bqIoa7P0JWE=,iv:LcLCUVytOvCEYhbIG0h/CV69wH2s8rPYemnGe/3q7jE=,tag:cl5rxSt+G7Il9h3KuWgY/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
