apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: buildkit-git-image
  namespace: argo-workflows

spec:
  entrypoint: build

  volumes:
    - name: workspace
      emptyDir: {}

  templates:
    # Step 1: Clone source
    - name: clone
      container:
        image: alpine/git:v2.45.2
        command:
          - sh
          - -c
        args:
          - |
            git clone https://github.com/wisphill/apps.git /workspace
            ls -la /workspace

        volumeMounts:
          - name: workspace
            mountPath: /workspace

    # Step 2: Build image with BuildKit
    - name: build
      container:
        image: moby/buildkit:v0.25.1-rootless

        command:
          - buildctl-daemonless.sh

        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox

        args:
          - build
          - --frontend
          - dockerfile.v0

          - --local
          - context=/workspace

          - --local
          - dockerfile=/workspace

          - --output
          - type=oci,dest=/workspace/apps-image.tar

        volumeMounts:
          - name: workspace
            mountPath: /workspace
