apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: buildkit-git-image
  namespace: argo-workflows

spec:
  entrypoint: build
  serviceAccountName: workflow-runner

  templates:
    - name: build

      volumes:
        - name: workspace
          emptyDir: {}

      # use the container set to make sure workflow pods are in the same node
      containerSet:
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: buildkit-config
            mountPath: /etc/buildkit/buildkitd.toml
            subPath: buildkitd.toml
        containers:
          - name: clone
            image: alpine/git:v2.45.2
            command:
              - sh
              - -c
            args:
              - |
                set -ex
                git clone https://github.com/wisphill/apps.gin.git /workspace
                ls -lah /workspace

          # buildkit build, then push to docker registry
          - name: build
            image: moby/buildkit:v0.25.1-rootless
            dependencies:
              - clone
            command:
              - buildctl-daemonless.sh
            env:
              - name: BUILDKITD_FLAGS
                value: --oci-worker-no-process-sandbox --config=/etc/buildkit/buildkitd.toml
            args:
              - build
              - --frontend
              - dockerfile.v0
              - --local
              - context=/workspace
              - --local
              - dockerfile=/workspace
              - --output
              - type=image,name=docker-registry.docker-registry.svc.cluster.local:5000/apps/gin:latest,push=true
