apiVersion: v1
kind: Secret
metadata:
    name: argo-workflows-secret-keys
    namespace: argo-workflows
type: Opaque
stringData:
    SSO_CLIENT_ID: ENC[AES256_GCM,data:bQWHXaiDsdme5idMS8qncMHDAwmSw+J+KUCJ6mxgSoN89g9QSQ3LHg==,iv:KIq7KbL9UKx9D4p1egeW285JVqcc4qIFinU9b4rs+IE=,tag:uHW+Oi0CtLa4p/OkYNzWqg==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:8Q5brzmd0MP9fKADbu09k9cknkMAa79R3h5LjycJFoBOwBlP39/J1SnLgsJWuUkLbagN6Gj9mFuag6ltsEV2TEC+zOqpGxYjKid4BMbtvITHUb/QdtIngR4va4vv9GjDehP4V+RuVckwOwY1RbI/4mqN/ifmg9uFdxEfanRVKUk=,iv:kyrKrmRVME+UijDwBZecq/liP6pOy1mi7Cp3RkWThnc=,tag:igBQnO07sDkvjd/ScDo2HQ==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T03:46:21Z"
    mac: ENC[AES256_GCM,data:t1bgVRvEW/6zv6cBqUAZmiD0oX7yYgvFLCAYEHEpRFFiM43hnf2nOdCmR6AW1qQDL9jW8ysVlBw5D49zif3UcDI88Em8OTBJ9j+SeIAjhSjtZzuAXchFVa9SxMxsc6Zy1zSv29YzQzwqDLejDtxv8zJJ+YD/IxbfaeQsQidrwWo=,iv:3Mb92+0B0hPOk/4MUIVKhS18MJQH4WpSiLwTuAturWA=,tag:LojepXUOjljrVU6IIw79bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
