apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: platform
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:388BYbEI9IPr6M2NePo2/EbgHE0=,iv:fwenr5S8e7gfTaR8USkJE700+DM1dRVW2H+3MOG3Fio=,tag:ZdvGhbBlIChIXj5VQtSetA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:ge3V/Yya7CKmaPUBb70CRxU37AaqwzGJ3yxKzKviZ/tEbiANDFUDoQ==,iv:+TslPLulFu/VQprlDG+0F/92B0mBx4N+YhXGRmxBC0g=,tag:z/256VJnTZIFhRm/EEuWlg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:Hx/7oEOwgFj8ZhRouGrPyk4mkemAhDWQsm1gbZZbCH/z6hXpBe7xYgGVhsMXrYWBOwGjHG2hAcGqMwKHGP0iQw==,iv:YJ+q1wKjfnrdcKiFABCp5iN2u828rHorFTu8fGsvOTw=,tag:ZP4FjEn73cQZq2b1tJU0wA==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T12:08:35Z"
    mac: ENC[AES256_GCM,data:iYEnugRDBpbbFOy2iHo86jrMNaukCEiKhbfJPgJa7RttmwyWJ3dVC3l7bdhuwsR2S2F6imuHKkc4qPZW/GGRzfjnXAVT8otDaTfpOsORbSci8/itf7RfVy+Uhl646pC6xB1vzrZs5M0G/XSbl3kzRANMDJABg0mzb1XLxJ5MAt8=,iv:Pizr55mT77LmES4Z+11l7ul8e/nivuA0YIhwrTHnK08=,tag:+/s9S9T5Ggj3qwIaD+3Khg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
