apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: platform
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:388BYbEI9IPr6M2NePo2/EbgHE0=,iv:fwenr5S8e7gfTaR8USkJE700+DM1dRVW2H+3MOG3Fio=,tag:ZdvGhbBlIChIXj5VQtSetA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:ge3V/Yya7CKmaPUBb70CRxU37AaqwzGJ3yxKzKviZ/tEbiANDFUDoQ==,iv:+TslPLulFu/VQprlDG+0F/92B0mBx4N+YhXGRmxBC0g=,tag:z/256VJnTZIFhRm/EEuWlg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:pl7cK8vIsSDEloWKNoPiUnW5njpAhrMCdAyi6hNH5jY=,iv:hugvcK99XZhWO9sBVGtsnU5tpCf1fWl/1cxSvr7IGoE=,tag:Vq6G7Pq7PzOfm7zdkAgpeQ==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T12:13:19Z"
    mac: ENC[AES256_GCM,data:AjssOxEpr3shg0rkN/rnC6ABeRpDApF2hf//kVmHtjfgbgkLw3jWmwx3DWhXrobmxDAY+58TMFdXDKVg/lAxekrx0dD4MHy2Ksr682kBWOnU4Xa8I6ikSA9HggR2fHsacSoG+tbE9fwatgRU3CoW2LQEzTa99LTu7RW0Mhny8pg=,iv:x9+huznZCt/8WDLRluGlTfGVb/DVk5M/Z+w+WGIGio4=,tag:J/OVKLPxNni6GihrI4Pdsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
