apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: platform
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:388BYbEI9IPr6M2NePo2/EbgHE0=,iv:fwenr5S8e7gfTaR8USkJE700+DM1dRVW2H+3MOG3Fio=,tag:ZdvGhbBlIChIXj5VQtSetA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:ge3V/Yya7CKmaPUBb70CRxU37AaqwzGJ3yxKzKviZ/tEbiANDFUDoQ==,iv:+TslPLulFu/VQprlDG+0F/92B0mBx4N+YhXGRmxBC0g=,tag:z/256VJnTZIFhRm/EEuWlg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:kwQUhQLwGHtwR/79wPczmRZk5nl7hJot9SKwA/Nzr8QGfoBWYL/EeO8JZfA=,iv:WaGsIxsrc+klhqda7hYseixAqgL0tiQjtsmkrhM46d4=,tag:R9KTHRobSIq/mmexgEk+Lg==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T11:50:47Z"
    mac: ENC[AES256_GCM,data:pNPETFyqHnmUtQFdaGfKlv8oMMnYMKh8ymJ3SMwFFV3FUe3TjV9xicLV91VyWyZt2GaPGsJjZwleqN6NFD1WP7FtWqDXZ+o4LUZpCX9j4J+7Bvtz8h69uMS4fr1ngoHaXiJKsz5pAQXaxGu6LzZwejSad+ApZIXGHRfn/6BppE8=,iv:zV4daG3MosfjOiuulG1QHA8pGtVwg3FdZ5UnxX5xCN4=,tag:NQERPdM4fz95+RN+zxJ6Jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
