tempo:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      memory: 512Mi

persistence:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  enabled: true
  size: 3Gi

service:
  type: ClusterIP

storage:
  trace:
    backend: local
    path: /var/tempo/traces

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
