tempo:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      memory: 512Mi

  traces_storage:
    backend: local
  # recommended for production
  storage:
    path: /var/tempo/metrics

persistence:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  enabled: true
  size: 3Gi

service:
  type: ClusterIP
