apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:jzmvJ0g=,iv:pHU1Mvo11IWQJHqdQGlIhMRAvuhcIFPU0dt2FSxyadw=,tag:w+AzUqCEKYHNzLbriv236w==,type:str]
    admin-password: ENC[AES256_GCM,data:oCQj/5unnmkcLA==,iv:W977lMdpeDfAsapuO77PoM1jBgcTU46gJQibP9w3/mg=,tag:UqNR37ZKIJExmbE7YW5Fbg==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T13:15:56Z"
    mac: ENC[AES256_GCM,data:p69JlN7YdFiZJXukdtLODEpBgLixqr0gCCGPv2amD11iac8eObd+7TI7iLgmR5EcrJHY/GlGW8EOZKM01a9QtDUaINP60E9qvrQbh6GBQND80tfa4hkeXIABN/zrxzSD5pFpmc7TCrJxbjCE6cQ/Inf7XBP5ZIX4iO8CIfOThuc=,iv:6qfL3IfBnyhI5LHsuGSoHHIVLaYg7QE8bcSOsrBmTX8=,tag:teNQ0fEkOalxgu6quWKmJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
