apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:2KIq0zc=,iv:KTpKv8REOcwCSzNqFwMuwC5nQWanVqaUXon5QBjfiqY=,tag:ybqndHuTZvfgPDS4DchUGA==,type:str]
    admin-password: ENC[AES256_GCM,data:5ud/QJ9mb/9Ycg==,iv:6uz5T4wKegXSnLrDw7510HThAuPLMZJivnUwfyvIE1k=,tag:rmuBfUPEoaa+Q0rb+zfLWQ==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T10:48:28Z"
    mac: ENC[AES256_GCM,data:ETEQ5goYNojkh6Z7Oju5HXXEfJzU186joNTwVH/XoOcmYE2c+cjs3WsPw/FWpQ6JCBAq20bkewjSeajnroGnCMAi5+tllRTrcnfpiAoj1rzQwhMnftzINHAFYpyhjz5bLepT8BHg4jOFAgE/HED7zVPJ6vyvuAoc026RPuGoA9U=,iv:iFzLaB4s5agxD7subS6Xz+hLC52onylAU8LKGb68UVY=,tag:2bFGgMKiEaHc+xby/G26gA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
