apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:jzmvJ0g=,iv:pHU1Mvo11IWQJHqdQGlIhMRAvuhcIFPU0dt2FSxyadw=,tag:w+AzUqCEKYHNzLbriv236w==,type:str]
    admin-password: ENC[AES256_GCM,data:F+PPNgfuD9A8yg==,iv:prG2kgdmXZZheENg7vmEFAlPDTl2np5YzVg3sJa6ndk=,tag:sEaLzvTdyDeS5AGjQphMYg==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T13:26:03Z"
    mac: ENC[AES256_GCM,data:yOXt7p4BLD3qgu9a1iC6+eJGkU1q+NKAfP3tp68Hj14/5ive8d4oC54FgqaAKbLDQnOPNvguQV/xdXvMdGv6tDeubwvrrCOQhnP/aZ83/Dkg85s+xWkhufxTNWJfk+6aMu0BLXrAp9sum661b0tZ6HXKPfQrug24U9o+hG5njf4=,iv:JXERYpt5A9aOKGAnAA0LRyM3yTApEABP2TW4sZIfXEg=,tag:5/9uFfIzEseWDLFsJpDL1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
