apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: docker-registry
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://twuni.github.io/docker-registry.helm
      chart: docker-registry
      targetRevision: 2.2.3
      helm:
        valueFiles:
          - $values/gitops/docker-registry/values.yaml

    - repoURL: https://github.com/wisphill/ops-infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: docker-registry

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
