apiVersion: v1
kind: Secret
metadata:
    name: glance-secrets
    namespace: glance
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:k6Q5jv/+uIn3c+ydlJak8J0PwNkN149XVn45IYaXTgaTbi7aQWBn/A==,iv:ZKpox78T81F2zDUKhDJyg4IuxK7iqjNQ/JgpGLov62w=,tag:+RyfE7M3LB9BmZSX27mJZA==,type:str]
sops:
    age:
        - recipient: age1fg2mcvwuztl4cgycxhdlfzu584uslnfznmgunqgw99znwmqhjq3quxdmw3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFBlMVJZTDVkV3JremFH
            bk9STExPMW5ycHpWbi9aSk1qSEdXajhwT3c0CkQ5bEZuOXdIbmRGbE5OKytJM080
            anRyVlNWbHVWQmxwT0VZZ0ZzUUxnMFUKLS0tIDgxdXczVTFsZDNyVlRUdElsUmpK
            cElab3RFWEgyTnV4Zy91b3hiV2MvRW8K1GikcQlcN8gCeZy8Fzbb9NLFaeZCgAJX
            y87tv/RRtOTk/zkBE+dOC8p4KX3vq9bFroT9iYnuKDlnvHKIyfmFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T03:38:45Z"
    mac: ENC[AES256_GCM,data:yS8ugmFYkPnbEf66gDX0CMJDbJMC80vD4O23XqdmLA4brBAccP+QqOD84mTGVnh7TkPyGY2sdsf/7iBohRoX+5nvFsMKr8VqzRHlK8UW0wkmYCfy9T4ibvEa1Gi2Cf1vSw2DmreENg6eP4L+Bo/VXvxQRLSt0IwxH15eW1Cqzwo=,iv:XrJy2sv2g1lhqLrw/j0ADuu5efy0vxlJAHEsAqpISaA=,tag:G+e4aUveIj7hY9Ab+46D8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
