apiVersion: v2
name: api-hello
description: Hello API
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: base-service
    version: 0.1.0
    repository: "file://../base-service-chart"
