base-service:
  app:
    name: api-hello

  replicaCount: 2

  image:
    repository: hashicorp/http-echo
    tag: "1.0"
    pullPolicy: IfNotPresent

  container:
    port: 5678

  command:
    - /http-echo

  args:
    - "-text=hello from hashicorp"

  service:
    type: ClusterIP
    port: 80
    targetPort: 5678

  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 100m
      memory: 64Mi
