apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: platform
data:
  conf.yml: |
    pageInfo:
      title: Phil Homelab

    sections:
      - name: Monitoring
        items:
          - title: Grafana
            url: https://grafana.opswork.io.vn
            icon: grafana

          - title: Prometheus
            url: https://prometheus.opswork.io.vn
            icon: prometheus

      - name: GitOps
        items:
          - title: ArgoCD
            url: https://argocd.yuu.dev
            icon: argo-cd
