apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: platform
data:
  conf.yml: |
    appConfig:
      theme: high-constrast-light
      hideComponents:
      preventWriteToDisk: true
      disableConfigurationForNonAdmin: true
      hideComponents:
        hideFooter: true


    pageInfo:
      title: Phil Homelab
      description: Kubernetes • Observability • GitOps
      footerText: Phil Homelab • Kubernetes • Observability • GitOps

    sections:
      - name: Monitoring
        items:
          - title: GitHub
            description: Source Code, Issues and Pull Requests
            icon: https://cdn.simpleicons.org/github
            url: https://github.com/wisphill

          - title: Grafana
            url: https://grafana.opswork.io.vn
            icon: https://cdn.simpleicons.org/grafana

          - title: Prometheus
            url: https://prometheus.opswork.io.vn
            icon: https://cdn.simpleicons.org/prometheus

      - name: GitOps
        items:
          - title: ArgoCD
            url: https://argocd.yuu.dev
            icon: https://cdn.simpleicons.org/argo
