apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.6.2
    helm:
      releaseName: monitoring
      # one prometheus instance is enough for most use cases.
      # disable the node exporter because I am using K8S on WSL, WSL does not share the mount events to containers
      values: |
        prometheusOperator:
          enabled: true
        grafana:
          enabled: false
        nodeExporter:
          enabled: false
        alertmanager:
          enabled: true
        prometheus:
          prometheusSpec:
            retention: 15d
            retentionSize: 800MiB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # for big custom resources CRD like the Prometheus
