apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          ports:
            - containerPort: 4180
          envFrom:
            - secretRef:
                name: oauth2-proxy-secret
          args:
            - --provider=github
            - --github-org=Ywisper
            - --email-domain=*
            - --scope=user:email,read:org
            - --http-address=0.0.0.0:4180
            - --reverse-proxy=true
            - --cookie-secure=true
            - --cookie-domain=.opswork.io.vn
            - --whitelist-domain=.opswork.io.vn
            - --set-xauthrequest=true
