apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 12.8.0
      helm:
        valueFiles:
          - $values/gitops/grafana/values.yaml

    - repoURL: https://github.com/wisphill/ops-infrastructure.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/wisphill/ops-infrastructure
      targetRevision: main
      path: gitops/grafana
      plugin:
        name: ksops

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
