admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  type: pvc
  storageClassName: local-path
  size: 3Gi
  accessModes:
    - ReadWriteOnce
  finalizers:
    - kubernetes.io/pvc-protection
